version: "3.8"
services:
  app:
    image: ja-ghminer:latest
    container_name: ja_ghminer
    restart: unless-stopped
    build: .
    volumes:
      - './logs:/app/logs'
      - './lib/config/miner.yml:/app/lib/config/miner.yml'
    env_file:
      - .env
    ports:
      - "${PORT}:4567"
    links:
      - mongodb
    networks:
      - mongo-net

  mongodb:
    image: 'mongo:latest'
    container_name: ja_ghminer_database
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - './volumes/database-volume:/data/db'
    networks:
      - mongo-net
volumes:
  mongodb_data:
    driver: local

networks:
  mongo-net:
