production:
  clients:
    default:
      database: <%= ENV['MONGO_INITDB_DATABASE'] %>
      hosts:
        - mongodb:27017
      options:
        server_selection_timeout: 5
        user: <%= ENV['MONGO_INITDB_ROOT_USERNAME'] %>
        password: <%= ENV['MONGO_INITDB_ROOT_PASSWORD'] %>
        auth_source: admin
development:
  clients:
    default:
      uri: mongodb://jaminer:password@mongodb:27017/ja-archive?retryWrites=true&w=majority&authSource=admin
      options:
        server_selection_timeout: 5