name: Ruby-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Ruby
          uses: ruby/setup-ruby
          with:
            ruby-version: 3.0.0
    - name: Cache Ruby Gems
          uses: actions/cache@v2
          with:
            path: vendor/bundle
            key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-gems-

        - name: Bundle Install
          run: |
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
    - name: Run Tests
    - name: Formatting and Security Checks
          run: |
            bundle exec rubocop
            bundle exec brakeman -z
            gem install bundle-audit
            bundle-audit update
            bundle-audit
